apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-artifactory-tekton-11apr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-artifactory-tekton-11apr 
  name: go-artifactory-tekton-11apr
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-artifactory-tekton-11apr 
